# Generated by Django 4.2.2 on 2023-08-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='作者表id')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='姓名')),
                ('sex', models.CharField(default='male', max_length=6, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='作者详细信息表id')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('address', models.CharField(max_length=100, verbose_name='住址')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='出版社id')),
                ('name', models.CharField(max_length=48, unique=True, verbose_name='出版社名称')),
                ('city', models.CharField(max_length=48, verbose_name='注册地')),
                ('email', models.CharField(max_length=48, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='书籍表id')),
                ('bname', models.CharField(max_length=16, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('publishDate', models.DateField(verbose_name='出版日期')),
                ('authors', models.ManyToManyField(to='root.author', verbose_name='中间表')),
                ('publishs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.publish', verbose_name='外键')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='authorDetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root.authordetail', verbose_name='外键'),
        ),
    ]
