# Generated by Django 4.2.5 on 2023-09-25 12:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', 'man'), ('2', 'feman')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('telphone', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(max_length=50, verbose_name='办公地址')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=50, verbose_name='出版社名称')),
                ('city', models.CharField(max_length=50, verbose_name='出版社注册地址')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('bname', models.CharField(max_length=50, verbose_name='书籍名称')),
                ('publish_date', models.DateField(verbose_name='出版日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('authors', models.ManyToManyField(to='app01.author', verbose_name='中间表')),
                ('publishs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.publish', verbose_name='外键，出版社表id')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='author_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.authordetail', verbose_name='外键，作者详情表id, 一对一关系'),
        ),
    ]
