# Generated by Django 4.2.2 on 2023-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='book表id')),
                ('bname', models.CharField(max_length=50, verbose_name='书籍名称')),
                ('price', models.FloatField(default=1.0, verbose_name='价格')),
                ('publishDate', models.DateField(auto_now=True, verbose_name='出版日期')),
                ('publisher', models.CharField(max_length=50, verbose_name='出版社')),
            ],
        ),
    ]
