# Generated by Django 4.2.2 on 2023-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='123456', max_length=32, verbose_name='密码')),
            ],
        ),
    ]
