# Generated by Django 4.2.2 on 2023-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bname',
            field=models.CharField(max_length=50, unique=True, verbose_name='书籍名称'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateField(verbose_name='出版日期'),
        ),
    ]
