# Generated by Django 4.2.1 on 2023-07-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '二椅子')], default=1, unique=True)),
                ('current_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
