# Generated by Django 4.2.2 on 2023-07-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_author_authordetail_publish_book_author_authordetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='root.author', verbose_name='中间表, root_book_authors'),
        ),
    ]
