# Generated by Django 4.2.1 on 2023-07-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_id',
            new_name='publish',
        ),
    ]
