# Generated by Django 4.2.2 on 2023-07-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('mobile', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=16, unique=True, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', 'male'), ('2', 'female')], default='1', max_length=1, verbose_name='性别, 1-male, 2-female, 默认 1')),
                ('authorDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root.authordetail', verbose_name='作者详细表id, 外键')),
            ],
        ),
    ]
