# Generated by Django 4.2.2 on 2023-07-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_publish_alter_authordetail_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_id',
            new_name='publish',
        ),
    ]
