# Generated by Django 4.2.2 on 2023-07-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', 'male'), ('2', 'female')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('mobile', models.CharField(max_length=16, verbose_name='电话')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('bname', models.CharField(max_length=50, verbose_name='书籍名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('publishDate', models.DateField(verbose_name='出版日期')),
                ('authors', models.ManyToManyField(to='root.author', verbose_name='中间表, root_book_author')),
                ('publishs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.publish', verbose_name='外键,出版社id')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='authorDetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root.authordetail', verbose_name='外键'),
        ),
    ]
