# Generated by Django 4.2.2 on 2023-07-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_publish_name_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish', to='root.publish', verbose_name='外键,出版社id'),
        ),
    ]
