# Generated by Django 4.2.2 on 2023-07-30 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_book_publishs'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.IntegerField(default=1, verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='book',
            name='good',
            field=models.IntegerField(default=1, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.publish', verbose_name='外键,出版社id'),
        ),
    ]
