# Generated by Django 4.2.1 on 2023-08-01 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(max_length=21, verbose_name='姓名')),
                ('sex', models.CharField(default='male', max_length=6, verbose_name='性别,默认male')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('telphone', models.CharField(max_length=20, verbose_name='电话')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(max_length=50, verbose_name='出版社名称')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, unique=True, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('title', models.CharField(max_length=50, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('publishDate', models.DateField(verbose_name='出版日期')),
                ('authors', models.ManyToManyField(to='root.author', verbose_name='中间表, root_book_authors')),
                ('publishs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.publish', verbose_name='外键')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='authorDetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root.authordetails', verbose_name='外键'),
        ),
    ]
