# Generated by Django 4.2.2 on 2023-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '不详')], default=1, unique=True)),
                ('birth', models.DateField()),
            ],
        ),
    ]
